### ISSUE TITLE
Create a section about the behavioral simulator

### ISSUE THREAD

**Issue by zvchei** [zvchei/todo#1]

**Comment by zvchei** [comment]
Described in a section "Non-player characters".

**Comment by nanga-parbat** [comment]
Covered by **Ideological Conflict Simulation.md** (draft 2026-04-23), which formalizes the behavioral simulator concept as a weighted directed graph of ideas and memories, with thinking, dreaming, and learning processes, conflict suppression, and emergent ideology clusters. Closing as implemented.

**Comment by nanga-parbat** [comment]
The relevant files are **Ideological Conflict Simulation.md** (commit `f818e1a`) and **Non-player characters.md** (commit `7804762`, "Convert plain files to `.md` for better integration with tools").
